# Rscript --vanilla /ddn/gs1/home/li11/ddnDrive/project2019/SEM/rscripts/calculate_index_streamline_linux_w_arguments.R  /ddn/gs1/home/li11/ddnDrive/project2019/SEM/data/new_t_scores_w_lev_03272019.rda  /ddn/gs1/home/li11/ddnDrive/project2019/SEM/shinyRelated/testNewBootstrapResults/EliminationWithReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/shinyRelated/testNewBootstrapResults/EliminationWithoutReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/rscripts/helpScripts/SEM_util.R   /ddn/gs1/home/li11/ddnDrive/project2019/SEM/shinyRelated/testNewBootstrapResults/ 

Rscript --vanilla /ddn/gs1/home/li11/ddnDrive/project2019/SEM/rscripts/calculate_index_streamline_linux_w_arguments.R  /ddn/gs1/home/li11/ddnDrive/project2019/SEM/data/new_t_scores_w_lev_03272019.rda /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/ChemDrug_184_results/EliminationWithReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/ChemDrug_184_results/EliminationWithoutReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/rscripts/helpScripts/SEM_util.R  /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/ChemDrug_184_results/ChemDrug184_index.txt  

Rscript --vanilla /ddn/gs1/home/li11/ddnDrive/project2019/SEM/rscripts/calculate_index_streamline_linux_w_arguments.R  /ddn/gs1/home/li11/ddnDrive/project2019/SEM/data/new_t_scores_w_lev_03272019.rda /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/ChemToxinAgent_42_results/EliminationWithReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/ChemToxinAgent_42_results/EliminationWithoutReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/rscripts/helpScripts/SEM_util.R  /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/ChemToxinAgent_42_results/ChemToxAgent_42_index.txt  

#Rscript --vanilla /ddn/gs1/home/li11/ddnDrive/project2019/SEM/rscripts/calculate_index_streamline_linux_w_arguments.R  /ddn/gs1/home/li11/ddnDrive/project2019/SEM/data/new_t_scores_w_lev_03272019.rda /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/KEGG_analysis/EliminationWithReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/KEGG_analysis/EliminationWithoutReplacement/ /ddn/gs1/home/li11/ddnDrive/project2019/SEM/IPA/KEGG_analysis/KEGG_28_index.txt



